# Generated by Django 2.0.3 on 2018-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
