# Generated by Django 2.0.3 on 2018-04-06 07:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180406_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='scoring',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
