# Generated by Django 2.0.3 on 2018-04-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180406_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_question', to='chat.Question'),
        ),
    ]
